### PR TITLE
Patches

### PR DESCRIPTION
**Pull request by lassik**
A couple more things.

### CODE REVIEW

**Review by cgay — APPROVED** [review]

**Comment by lassik** [comment]
@housel OK?

**Comment by housel** [comment]
I was waiting to see if the issues in #60 would be addressed.

**Comment by lassik** [comment]
The above fix should do it, but I haven't tested.

**Comment by pedro-w** [comment]
On my Emacs 27.1 I still get these warnings in the Compile-Log
```
Compiling file /Users/peterhull/Projects/dylan-mode/dime-repl.el at Sun Mar 28 11:35:58 2021
dime-repl.el:1487:7:Warning: assignment to free variable
    ‘dime-output-target-to-marker-function’
dime-repl.el:1488:7:Warning: assignment to free variable
    ‘dime-write-string-function’

In end of data:
dime-repl.el:1496:1:Warning: the function ‘dime-emit-to-target’ is not known
    to be defined.
```
But the errors I reported in #60 seem to be fixed by this last commit, thanks!

It would be good to address those warnings if it's possible, but not critical I suppose (AFAICS a lot of melpa packages throw up warnings when they're compiled)

**Comment by lassik** [comment]
Not sure what's going on. I don't get compiler warnings on 27.1. Did you try restarting Emacs and recompiling the .el files?

**Comment by pedro-w** [comment]
I did a `(byte-recompile-directory "." 0 t)` but I will redo it more carefully with a clean start and check I'm not picking up any old files from somewhere.

**Comment by pedro-w** [comment]
OK, no warnings or errors if I start emacs with `EMACSLOADPATH=$(pwd): emacs -q` then recompile all files.
As far as I can tell this is ready for merging.

**Review by housel — APPROVED** [review]

**Pull request merged**
